CREATE TABLE IF NOT EXISTS users_tbl(
  id BIGINT AUTO_INCREMENT NOT NULL,
  u_id VARCHAR(256) NOT NULL,
  u_name VARCHAR(50) NOT NULL,
  u_username VARCHAR(50) NOT NULL,
  u_password VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);